# Generated by Django 4.1.3 on 2022-11-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10)),
                ("price", models.FloatField()),
                ("change", models.JSONField()),
                ("mcap", models.BigIntegerField()),
                ("volume", models.JSONField()),
                ("c_supply", models.BigIntegerField()),
            ],
            options={
                "ordering": ["-mcap"],
            },
        ),
    ]
