# Generated by Django 4.1.3 on 2022-11-06 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={},
        ),
        migrations.RemoveField(
            model_name="currency",
            name="c_supply",
        ),
        migrations.RemoveField(
            model_name="currency",
            name="change",
        ),
        migrations.RemoveField(
            model_name="currency",
            name="mcap",
        ),
        migrations.RemoveField(
            model_name="currency",
            name="name",
        ),
        migrations.RemoveField(
            model_name="currency",
            name="price",
        ),
        migrations.RemoveField(
            model_name="currency",
            name="symbol",
        ),
        migrations.RemoveField(
            model_name="currency",
            name="volume",
        ),
        migrations.AddField(
            model_name="currency",
            name="data",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="currency",
            name="source",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="currency",
            name="updated_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
