# Generated by Django 4.1.3 on 2022-11-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_currency_options_remove_currency_c_supply_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Currency",
        ),
    ]
